name: Auto Merge Dependency Updates

on:
  - pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@a667af6f84e72a99c162539226127b3207d57839
        with:
          repo-token: ${{ secrets.CI_GITHUB_TOKEN }}
          allowed-actors: renovate[bot]
